// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package internal

import (
	"github.com/ONSdigital/dp-graph/v3/neo4j/neo4jdriver"
	"github.com/ONSdigital/golang-neo4j-bolt-driver"
	"sync"
)

var (
	lockClosableDriverPoolMockClose    sync.RWMutex
	lockClosableDriverPoolMockOpenPool sync.RWMutex
)

// Ensure, that ClosableDriverPoolMock does implement neo4jdriver.ClosableDriverPool.
// If this is not the case, regenerate this file with moq.
var _ neo4jdriver.ClosableDriverPool = &ClosableDriverPoolMock{}

// ClosableDriverPoolMock is a mock implementation of neo4jdriver.ClosableDriverPool.
//
//     func TestSomethingThatUsesClosableDriverPool(t *testing.T) {
//
//         // make and configure a mocked neo4jdriver.ClosableDriverPool
//         mockedClosableDriverPool := &ClosableDriverPoolMock{
//             CloseFunc: func() error {
// 	               panic("mock out the Close method")
//             },
//             OpenPoolFunc: func() (golangNeo4jBoltDriver.Conn, error) {
// 	               panic("mock out the OpenPool method")
//             },
//         }
//
//         // use mockedClosableDriverPool in code that requires neo4jdriver.ClosableDriverPool
//         // and then make assertions.
//
//     }
type ClosableDriverPoolMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// OpenPoolFunc mocks the OpenPool method.
	OpenPoolFunc func() (golangNeo4jBoltDriver.Conn, error)

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// OpenPool holds details about calls to the OpenPool method.
		OpenPool []struct {
		}
	}
}

// Close calls CloseFunc.
func (mock *ClosableDriverPoolMock) Close() error {
	if mock.CloseFunc == nil {
		panic("ClosableDriverPoolMock.CloseFunc: method is nil but ClosableDriverPool.Close was just called")
	}
	callInfo := struct {
	}{}
	lockClosableDriverPoolMockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	lockClosableDriverPoolMockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//     len(mockedClosableDriverPool.CloseCalls())
func (mock *ClosableDriverPoolMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	lockClosableDriverPoolMockClose.RLock()
	calls = mock.calls.Close
	lockClosableDriverPoolMockClose.RUnlock()
	return calls
}

// OpenPool calls OpenPoolFunc.
func (mock *ClosableDriverPoolMock) OpenPool() (golangNeo4jBoltDriver.Conn, error) {
	if mock.OpenPoolFunc == nil {
		panic("ClosableDriverPoolMock.OpenPoolFunc: method is nil but ClosableDriverPool.OpenPool was just called")
	}
	callInfo := struct {
	}{}
	lockClosableDriverPoolMockOpenPool.Lock()
	mock.calls.OpenPool = append(mock.calls.OpenPool, callInfo)
	lockClosableDriverPoolMockOpenPool.Unlock()
	return mock.OpenPoolFunc()
}

// OpenPoolCalls gets all the calls that were made to OpenPool.
// Check the length with:
//     len(mockedClosableDriverPool.OpenPoolCalls())
func (mock *ClosableDriverPoolMock) OpenPoolCalls() []struct {
} {
	var calls []struct {
	}
	lockClosableDriverPoolMockOpenPool.RLock()
	calls = mock.calls.OpenPool
	lockClosableDriverPoolMockOpenPool.RUnlock()
	return calls
}
